--------------------------------------------------------
--  File created - Wednesday-August-05-2026   
--------------------------------------------------------
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_ATTRIBUTES.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_NODE_TYPES.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_SQL.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_PRJ_STT_PRM_USR.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_GROUPROLES.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_ROLES.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_VIEWS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_USERS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_NODES.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_PERMISSIONS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_ROLEPERMISSIONS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_PERMISSIONS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_CONTEXTS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_GROUPS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_USERPERMISSIONS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_UNITSSTATUS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_XSTATUS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_NODE_ATTRIBUTE_VALUE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_ATTRIBUTES_PROPERTIES.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_USERGROUPS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_ATTRIBUTES_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_NODE_TYPES_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_SQL_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_PRJ_STT_PRM_USR_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_GROUPROLES_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_ROLES_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_VIEWS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_USERS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_NODES_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_PERMISSIONS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_ROLEPERMISSIONS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_PERMISSIONS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_CONTEXTS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_GROUPS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_USERPERMISSIONS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_UNITSSTATUS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_XSTATUS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_NODE_ATTRIBUTE_VALUE_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_ATTRIBUTES_PROPERTIES_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_USERGROUPS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_NODE_TYPES_CONSTRAINT.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_ROLES_CONSTRAINT.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_USERS_CONSTRAINT.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_PERMISSIONS_CONSTRAINT.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUB_CONTEXTS_CONSTRAINT.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\New folder\UNITSHUBX_GROUPS_CONSTRAINT.sql
