--------------------------------------------------------
--  File created - Monday-August-03-2026   
--------------------------------------------------------
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_ACTIONS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_ROLEPERMISSIONS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_PERMISSIONS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_GROUPS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_GROUPROLES.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_UNITSSTATUS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_RESOURCES.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_SQL.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_NODES.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_PRJ_STT_ACT_USR.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_ATTRIBUTES.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_ROLES.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_ATTRIBUTES_PROPERTIES.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_NODE_TYPES.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_VIEWS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_USERGROUPS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_USERPERMISSIONS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_USERS.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_NODE_ATTRIBUTE_VALUE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_ACTIONS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_ROLEPERMISSIONS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_PERMISSIONS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_GROUPS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_GROUPROLES_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_UNITSSTATUS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_RESOURCES_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_SQL_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_NODES_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_PRJ_STT_ACT_USR_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_ATTRIBUTES_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_ROLES_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_ATTRIBUTES_PROPERTIES_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_NODE_TYPES_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_VIEWS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_USERGROUPS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_USERPERMISSIONS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_USERS_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_NODE_ATTRIBUTE_VALUE_DATA_TABLE.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_PERMISSIONS_CONSTRAINT.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_GROUPS_CONSTRAINT.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_RESOURCES_CONSTRAINT.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_ROLES_CONSTRAINT.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_NODE_TYPES_CONSTRAINT.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_USERPERMISSIONS_CONSTRAINT.sql
@\\eskanbank.com\EBUP\EBU\2271\Desktop\DB\UnitsHub\UNITSHUB_USERS_CONSTRAINT.sql
