--------------------------------------------------------
--  DDL for Index PK_PRJ_STS_ACTN_USRS
--------------------------------------------------------

  CREATE UNIQUE INDEX "INAP"."PK_PRJ_STS_ACTN_USRS" ON "INAP"."UNITSHUB_PRJ_STS_ACTN_USRS" ("PROJECT_ID", "ACTION_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;
