--------------------------------------------------------
--  DDL for Index PK_PROJECTSUBSTATUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "INAP"."PK_PROJECTSUBSTATUS" ON "INAP"."UNITSHUB_PROJECTSUBSTATUS" ("PROJECT_ID", "STATE_ID", "SUBSTATE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;
