REM INSERTING into INAP.UNITSHUB_PROJECTSTATUS
SET DEFINE OFF;
Insert into INAP.UNITSHUB_PROJECTSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR,PROJECT_ID) values ('Vacant','0000','Ready To Reserve','#eaec79','#000000','#ffffff','#1e293b','0017');
Insert into INAP.UNITSHUB_PROJECTSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR,PROJECT_ID) values ('Reserved','0512','Waiting 1st Payment','#fea710','#000000','#ffffff','#1e293b','0017');
Insert into INAP.UNITSHUB_PROJECTSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR,PROJECT_ID) values ('Sold','0768',null,'#297f29','#ffffff','#fffa5c','#1e293b','0017');
Insert into INAP.UNITSHUB_PROJECTSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR,PROJECT_ID) values ('Handed Over','5120',null,'#ff9500','#000000','#ffffff','#1e293b','0017');
