REM INSERTING into INAP.UNITSHUB_DOC2ENTITY
SET DEFINE OFF;
Insert into INAP.UNITSHUB_DOC2ENTITY (ENTITY_ID,CATEGORY_ID) values ('0001','0001');
Insert into INAP.UNITSHUB_DOC2ENTITY (ENTITY_ID,CATEGORY_ID) values ('0002','0001');
Insert into INAP.UNITSHUB_DOC2ENTITY (ENTITY_ID,CATEGORY_ID) values ('0002','0002');
Insert into INAP.UNITSHUB_DOC2ENTITY (ENTITY_ID,CATEGORY_ID) values ('0001','0003');
Insert into INAP.UNITSHUB_DOC2ENTITY (ENTITY_ID,CATEGORY_ID) values ('0001','0004');
Insert into INAP.UNITSHUB_DOC2ENTITY (ENTITY_ID,CATEGORY_ID) values ('0002','0004');
Insert into INAP.UNITSHUB_DOC2ENTITY (ENTITY_ID,CATEGORY_ID) values ('0001','0005');
Insert into INAP.UNITSHUB_DOC2ENTITY (ENTITY_ID,CATEGORY_ID) values ('0002','0005');
