REM INSERTING into INAP.UNITSHUB_UNITSSTATUS
SET DEFINE OFF;
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS) values ('HANDED OVER');
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS) values ('HELD');
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS) values ('RESERVED');
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS) values ('SOLD');
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS) values ('VACANT');
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS) values ('MOCK-UP');
