REM INSERTING into INAP.UNITSHUBX_GROUPS
SET DEFINE OFF;
Insert into INAP.UNITSHUBX_GROUPS (GROUP_ID,GROUP_NAME,DESCRIPTION,IS_SYSTEM) values ('0001','Administrators','Full access','N');
Insert into INAP.UNITSHUBX_GROUPS (GROUP_ID,GROUP_NAME,DESCRIPTION,IS_SYSTEM) values ('0002','Manager',null,'N');
Insert into INAP.UNITSHUBX_GROUPS (GROUP_ID,GROUP_NAME,DESCRIPTION,IS_SYSTEM) values ('0003','User',null,'N');
