--------------------------------------------------------
--  DDL for Table UNITSHUB_ATTRIBUTES
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_ATTRIBUTES" 
   (	"PROJECT_ID" VARCHAR2(4 BYTE), 
	"NODE_TYPE_ID" VARCHAR2(3 BYTE), 
	"ATTRIBUTE_NAME" VARCHAR2(150 BYTE), 
	"DISPLAY_ORDER" NUMBER, 
	"DATA_TYPE" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;
