--------------------------------------------------------
--  Constraints for Table UNITSHUB_AUTOTRANSFER_DONE_D
--------------------------------------------------------

  ALTER TABLE "INAP"."UNITSHUB_AUTOTRANSFER_DONE_D" ADD CONSTRAINT "CK_ATD_D_TRANSACTION" CHECK (TRANSACTION IN ('D', 'C')) ENABLE;
  ALTER TABLE "INAP"."UNITSHUB_AUTOTRANSFER_DONE_D" MODIFY ("ENTRY" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_AUTOTRANSFER_DONE_D" MODIFY ("UNITPAYMENT_ID" NOT NULL ENABLE);
