--------------------------------------------------------
--  DDL for Table UNITSHUB_ATTRIBUTES_PROPERTIES
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_ATTRIBUTES_PROPERTIES" 
   (	"PROJECT_ID" VARCHAR2(4 BYTE), 
	"NODE_TYPE_ID" VARCHAR2(3 BYTE), 
	"NAME_IN_UI" VARCHAR2(150 BYTE), 
	"SEARCHABEL" VARCHAR2(1 BYTE), 
	"DISPLAY_ORDER" NUMBER, 
	"SHOW_IN_UI" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;
