REM INSERTING into INAP.UNITSHUB_PAYMENTPLANDETAILS
SET DEFINE OFF;
Insert into INAP.UNITSHUB_PAYMENTPLANDETAILS (DETAIL_ID,PLAN_ID,DESCRIPTION,PERCENT,AMOUNT) values ('1','1','Reservation','5%',null);
Insert into INAP.UNITSHUB_PAYMENTPLANDETAILS (DETAIL_ID,PLAN_ID,DESCRIPTION,PERCENT,AMOUNT) values ('2','1','Contract Signing','90%',null);
Insert into INAP.UNITSHUB_PAYMENTPLANDETAILS (DETAIL_ID,PLAN_ID,DESCRIPTION,PERCENT,AMOUNT) values ('3','1','Foundation','5%',null);
Insert into INAP.UNITSHUB_PAYMENTPLANDETAILS (DETAIL_ID,PLAN_ID,DESCRIPTION,PERCENT,AMOUNT) values ('1','2','Payment Completion','15%',null);
Insert into INAP.UNITSHUB_PAYMENTPLANDETAILS (DETAIL_ID,PLAN_ID,DESCRIPTION,PERCENT,AMOUNT) values ('2','2','Painting','20%',null);
Insert into INAP.UNITSHUB_PAYMENTPLANDETAILS (DETAIL_ID,PLAN_ID,DESCRIPTION,PERCENT,AMOUNT) values ('3','2','Designing','25%',null);
Insert into INAP.UNITSHUB_PAYMENTPLANDETAILS (DETAIL_ID,PLAN_ID,DESCRIPTION,PERCENT,AMOUNT) values ('4','2','Constructing','40%',null);
