REM INSERTING into INAP.UNITSHUB_ATTRIBUTES
SET DEFINE OFF;
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','000','ACCOUNT',1,'TEXT');
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','000','NAME_EN',2,'TEXT');
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','000','NAME_AR',3,'TEXT');
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','006','Plot',1,'TEXT');
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','006','House',2,'TEXT');
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','006','Road',3,'TEXT');
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','006','Block',4,'TEXT');
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','006','Plot Area',5,'TEXT');
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','006','Built up Area',6,'TEXT');
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','006','Type',7,'TEXT');
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','006','Price',8,'TEXT');
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','006','Status',9,'TEXT');
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','006','Title Deed',10,'TEXT');
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','006','Parcel No',11,'TEXT');
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','006','PAYMENTPLAN',12,'TEXT');
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','006','REFERENCE',13,'TEXT');
Insert into INAP.UNITSHUB_ATTRIBUTES (PROJECT_ID,NODE_TYPE_ID,ATTRIBUTE_NAME,DISPLAY_ORDER,DATA_TYPE) values ('0017','006','Comments',14,'TEXT');
