--------------------------------------------------------
--  DDL for Table UNITSHUB_SQL
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_SQL" 
   (	"PROJECT_ID" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"SQL_ID" VARCHAR2(20 BYTE), 
	"SQL_STATEMENT" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" 
 LOB ("SQL_STATEMENT") STORE AS SECUREFILE (
  TABLESPACE "INAP" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
