--------------------------------------------------------
--  DDL for Table UNITSHUB_CUSTOMERPROPERTIES
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_CUSTOMERPROPERTIES" 
   (	"NODE_ID" VARCHAR2(7 BYTE), 
	"CONTACT_ID" VARCHAR2(7 BYTE), 
	"STATUS" VARCHAR2(5 BYTE), 
	"START_DATE" VARCHAR2(20 BYTE), 
	"END_DATE" VARCHAR2(20 BYTE), 
	"UNIT_ACCOUNT" VARCHAR2(25 BYTE), 
	"CREATED_AT" VARCHAR2(20 BYTE), 
	"COMMENTS" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;

   COMMENT ON COLUMN "INAP"."UNITSHUB_CUSTOMERPROPERTIES"."STATUS" IS 'STATUS ID, it should be same of STATUS in UNITSHUB_NODE_ATTRIBUTE_VALUE';
   COMMENT ON COLUMN "INAP"."UNITSHUB_CUSTOMERPROPERTIES"."UNIT_ACCOUNT" IS 'User Account in which all payments regarding this unit is made';
   COMMENT ON COLUMN "INAP"."UNITSHUB_CUSTOMERPROPERTIES"."CREATED_AT" IS 'the Time in which this row is created in Unix format';
   COMMENT ON TABLE "INAP"."UNITSHUB_CUSTOMERPROPERTIES"  IS 'this table correlate customer to properties';
