--------------------------------------------------------
--  Constraints for Table UNITSHUB_ACTIONS
--------------------------------------------------------

  ALTER TABLE "INAP"."UNITSHUB_ACTIONS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ACTIONS" MODIFY ("NEED_PAYMENT" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ACTIONS" MODIFY ("RECEIVE_PARAMETERS_ENABLED" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ACTIONS" MODIFY ("SHOW_IN_PREVIEW" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ACTIONS" MODIFY ("SHOW_IN_DEFAULT" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ACTIONS" MODIFY ("ACTION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ACTIONS" MODIFY ("ACTION_TITLE" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ACTIONS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
