--------------------------------------------------------
--  DDL for Table UNITSHUB_DOC_CATEGORIES
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_DOC_CATEGORIES" 
   (	"CATEGORY_ID" VARCHAR2(4 BYTE), 
	"PROJECT_ID" VARCHAR2(7 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"SORT_ORDER" NUMBER(4,0), 
	"IS_ACTIVE" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;

   COMMENT ON COLUMN "INAP"."UNITSHUB_DOC_CATEGORIES"."PROJECT_ID" IS 'NULL = category used by every project';
   COMMENT ON TABLE "INAP"."UNITSHUB_DOC_CATEGORIES"  IS 'Groups of documents (Contracts, Authentication Documents, Unit Plans ...)';
