REM INSERTING into INAP.UNITSHUB_RESOURCES
SET DEFINE OFF;
Insert into INAP.UNITSHUB_RESOURCES (RESOURCE_ID,RESOURCE_NAME,RESOURCE_TYPE,URL,PARENT_ID,DISPLAY_ORDER,ICON,IS_ENABLED) values ('0001','Dashboard','FORM',null,null,null,null,'Y');
Insert into INAP.UNITSHUB_RESOURCES (RESOURCE_ID,RESOURCE_NAME,RESOURCE_TYPE,URL,PARENT_ID,DISPLAY_ORDER,ICON,IS_ENABLED) values ('0002','Users','FORM',null,null,null,null,'Y');
Insert into INAP.UNITSHUB_RESOURCES (RESOURCE_ID,RESOURCE_NAME,RESOURCE_TYPE,URL,PARENT_ID,DISPLAY_ORDER,ICON,IS_ENABLED) values ('0003','Units','Units',null,null,null,null,'Y');
