--------------------------------------------------------
--  Constraints for Table UNITSHUB_DOCUMENTS
--------------------------------------------------------

  ALTER TABLE "INAP"."UNITSHUB_DOCUMENTS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_DOCUMENTS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_DOCUMENTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_DOCUMENTS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_DOCUMENTS" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_DOCUMENTS" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);
