--------------------------------------------------------
--  DDL for Table UNITSHUB_PROJECTSUBSTATUS
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_PROJECTSUBSTATUS" 
   (	"PROJECT_ID" VARCHAR2(4 BYTE), 
	"STATE_ID" VARCHAR2(4 BYTE), 
	"SUBSTATE_ID" VARCHAR2(4 BYTE), 
	"SUBTITLE" VARCHAR2(200 BYTE), 
	"SORT_ORDER" NUMBER(4,0), 
	"STATUS_BG_COLOR" VARCHAR2(20 BYTE), 
	"STATUS_FG_COLOR" VARCHAR2(20 BYTE), 
	"SUBTITLE_BG_COLOR" VARCHAR2(20 BYTE), 
	"SUBTITLE_FG_COLOR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;
