REM INSERTING into INAP.UNITSHUBX_ROLES
SET DEFINE OFF;
Insert into INAP.UNITSHUBX_ROLES (ROLE_ID,ROLE_NAME,DESCRIPTION) values ('0001','Administrator',null);
Insert into INAP.UNITSHUBX_ROLES (ROLE_ID,ROLE_NAME,DESCRIPTION) values ('0002','Manager',null);
Insert into INAP.UNITSHUBX_ROLES (ROLE_ID,ROLE_NAME,DESCRIPTION) values ('0003','User',null);
