--------------------------------------------------------
--  DDL for Table UNITSHUB_AUTOTRANSFER_DONE_T
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_AUTOTRANSFER_DONE_T" 
   (	"UNITPAYMENT_ID" VARCHAR2(7 BYTE), 
	"NODE_ID" VARCHAR2(20 BYTE), 
	"CONTACT_ID" VARCHAR2(20 BYTE), 
	"PLAN_ID" VARCHAR2(10 BYTE), 
	"SEQ" VARCHAR2(10 BYTE), 
	"TRANO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;
