REM INSERTING into INAP.UNITSHUB_PROJECTSTATUS
SET DEFINE OFF;
Insert into INAP.UNITSHUB_PROJECTSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR,PROJECT_ID) values ('HANDED OVER','9216',null,'f7e494','000000','FFFFFF','000000','001');
Insert into INAP.UNITSHUB_PROJECTSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR,PROJECT_ID) values ('VACANT','0000','Ready To Reserve','f7e494','000000','FFFFFF','000000','001');
Insert into INAP.UNITSHUB_PROJECTSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR,PROJECT_ID) values ('HANDED OVER','9216',null,'f7e494','000000','FFFFFF','000000','002');
Insert into INAP.UNITSHUB_PROJECTSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR,PROJECT_ID) values ('VACANT','0000','Ready To Reserve','f7e494','000000','FFFFFF','000000','002');
Insert into INAP.UNITSHUB_PROJECTSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR,PROJECT_ID) values ('RESERVED','5120','Waiting Payment','E7e4A4','000000','FFFFFF','000000','002');
Insert into INAP.UNITSHUB_PROJECTSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR,PROJECT_ID) values ('SOLD','0512',null,'#39a300','#ffffff','#ffffff','#1e293b','001');
Insert into INAP.UNITSHUB_PROJECTSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR,PROJECT_ID) values ('23423','1024','45654654','#4f46e5','#ffffff','#ffffff','#1e293b','002');
Insert into INAP.UNITSHUB_PROJECTSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR,PROJECT_ID) values ('Release','1024','Waiting Payment','#d7fee3','#000000','#ffffff','#1e293b','001');
