--------------------------------------------------------
--  DDL for Table UNITSHUB_ATTRIBUTES_PROPERTIES
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_ATTRIBUTES_PROPERTIES" 
   (	"PROJECT_ID" VARCHAR2(4 BYTE), 
	"NODE_TYPE_ID" VARCHAR2(3 BYTE), 
	"NAME_IN_UI" VARCHAR2(150 BYTE), 
	"SEARCHABEL" VARCHAR2(1 BYTE), 
	"DISPLAY_ORDER" NUMBER, 
	"SHOW_IN_UI" VARCHAR2(2 BYTE), 
	"CONTROL_WEHN_EDIT" VARCHAR2(20 BYTE), 
	"SQL" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;

   COMMENT ON COLUMN "INAP"."UNITSHUB_ATTRIBUTES_PROPERTIES"."CONTROL_WEHN_EDIT" IS 'when used in Edit, what is the most probalbe control to use: TextBox, List, etc
';
   COMMENT ON COLUMN "INAP"."UNITSHUB_ATTRIBUTES_PROPERTIES"."SQL" IS 'this SQL is used if the control is DropDownList or RadioButtonList..etc';
