--------------------------------------------------------
--  DDL for Table UNITSHUB_CONTEXTS
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_CONTEXTS" 
   (	"CONTEXT_ID" NUMBER, 
	"PARENT_CONTEXT_ID" NUMBER, 
	"PROJECT_ID" VARCHAR2(5 BYTE), 
	"NODE_TYPE_ID" VARCHAR2(5 BYTE), 
	"NODE_TYPE_NAME" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;
