--------------------------------------------------------
--  DDL for Table UNITSHUB_ATTACHMENTS
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_ATTACHMENTS" 
   (	"ATTACHMENT_ID" VARCHAR2(7 BYTE), 
	"DOCUMENT_ID" VARCHAR2(7 BYTE), 
	"COMMENT_ID" VARCHAR2(7 BYTE), 
	"FILE_NAME" VARCHAR2(255 BYTE), 
	"STORED_PATH" VARCHAR2(500 BYTE), 
	"CONTENT_TYPE" VARCHAR2(100 BYTE), 
	"FILE_SIZE" NUMBER(12,0), 
	"SORT_ORDER" NUMBER(4,0), 
	"CREATED_BY" VARCHAR2(5 BYTE), 
	"CREATED_AT" NUMBER(12,0), 
	"IS_ACTIVE" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;

   COMMENT ON COLUMN "INAP"."UNITSHUB_ATTACHMENTS"."STORED_PATH" IS 'Path on the server; the file is saved as <ATTACHMENT_ID>.<ext>';
   COMMENT ON TABLE "INAP"."UNITSHUB_ATTACHMENTS"  IS 'Uploaded files; each belongs to exactly one document or one comment';
