--------------------------------------------------------
--  DDL for Table UNITSHUB_RESOURCES
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_RESOURCES" 
   (	"RESOURCE_ID" VARCHAR2(5 BYTE), 
	"RESOURCE_NAME" VARCHAR2(200 BYTE), 
	"RESOURCE_TYPE" VARCHAR2(30 BYTE), 
	"URL" VARCHAR2(500 BYTE), 
	"PARENT_ID" NUMBER, 
	"DISPLAY_ORDER" NUMBER, 
	"ICON" VARCHAR2(100 BYTE), 
	"IS_ENABLED" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;
