--------------------------------------------------------
--  DDL for Table UNITSHUB_ACTIONS
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_ACTIONS" 
   (	"PROJECT_ID" VARCHAR2(5 BYTE), 
	"STATUS_ID" VARCHAR2(5 BYTE), 
	"ACTION_ID" VARCHAR2(5 BYTE), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"ACTION_TITLE" VARCHAR2(200 BYTE), 
	"ACTION_TYPE" VARCHAR2(20 BYTE), 
	"IMPLEMENTER_TITLE" VARCHAR2(200 BYTE), 
	"SHOW_IN_DEFAULT" NUMBER(1,0) DEFAULT 0, 
	"SHOW_IN_PREVIEW" NUMBER(1,0) DEFAULT 0, 
	"RECEIVE_PARAMETERS_ENABLED" NUMBER(1,0) DEFAULT 0, 
	"RECEIVE_PARAMETERS_MODE" VARCHAR2(20 BYTE), 
	"NEED_PAYMENT" NUMBER(1,0) DEFAULT 0, 
	"PAYMENT_PLAN_ID" VARCHAR2(50 BYTE), 
	"TO_STATUS_ID" VARCHAR2(50 BYTE), 
	"SCRIPT_TEXT" CLOB, 
	"PRE_EXECUTION" VARCHAR2(20 BYTE), 
	"CONFIRMATION_TEXT" VARCHAR2(500 BYTE), 
	"PARAMETER_TYPE" VARCHAR2(40 BYTE), 
	"FORM_TITLE" VARCHAR2(200 BYTE), 
	"SELECT_SQL" CLOB, 
	"CREATED_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" 
 LOB ("SCRIPT_TEXT") STORE AS SECUREFILE (
  TABLESPACE "INAP" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("SELECT_SQL") STORE AS SECUREFILE (
  TABLESPACE "INAP" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
