REM INSERTING into INAP.UNITSHUBX_USERGROUPS
SET DEFINE OFF;
Insert into INAP.UNITSHUBX_USERGROUPS (USER_ID,GROUP_ID) values ('2271','0001');
Insert into INAP.UNITSHUBX_USERGROUPS (USER_ID,GROUP_ID) values ('2463','0002');
Insert into INAP.UNITSHUBX_USERGROUPS (USER_ID,GROUP_ID) values ('2568','0003');
