--------------------------------------------------------
--  Constraints for Table UNITSHUB_ACTION_PLACEMENTS
--------------------------------------------------------

  ALTER TABLE "INAP"."UNITSHUB_ACTION_PLACEMENTS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ACTION_PLACEMENTS" MODIFY ("SUBSTATE_ID" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ACTION_PLACEMENTS" MODIFY ("STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ACTION_PLACEMENTS" MODIFY ("ACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ACTION_PLACEMENTS" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
