--------------------------------------------------------
--  Constraints for Table UNITSHUB_PROJECTSUBSTATUS
--------------------------------------------------------

  ALTER TABLE "INAP"."UNITSHUB_PROJECTSUBSTATUS" ADD CONSTRAINT "PK_PROJECTSUBSTATUS" PRIMARY KEY ("PROJECT_ID", "STATE_ID", "SUBSTATE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP"  ENABLE;
  ALTER TABLE "INAP"."UNITSHUB_PROJECTSUBSTATUS" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_PROJECTSUBSTATUS" MODIFY ("SUBTITLE" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_PROJECTSUBSTATUS" MODIFY ("SUBSTATE_ID" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_PROJECTSUBSTATUS" MODIFY ("STATE_ID" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_PROJECTSUBSTATUS" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
