--------------------------------------------------------
--  DDL for Table UNITSHUB_PAYMENTPLANDETAILS
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_PAYMENTPLANDETAILS" 
   (	"DETAIL_ID" VARCHAR2(20 BYTE), 
	"PLAN_ID" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"PERCENT" VARCHAR2(20 BYTE), 
	"AMOUNT" VARCHAR2(11 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;
