--------------------------------------------------------
--  DDL for Table UNITSHUB_ATP_GROUPS
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_ATP_GROUPS" 
   (	"PLAN_ID" VARCHAR2(5 BYTE), 
	"GROUP_ID" VARCHAR2(5 BYTE), 
	"GROUP_TITLE" VARCHAR2(200 BYTE), 
	"SORT_ORDER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;
