--------------------------------------------------------
--  Constraints for Table UNITSHUB_COMMENTS
--------------------------------------------------------

  ALTER TABLE "INAP"."UNITSHUB_COMMENTS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_COMMENTS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_COMMENTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_COMMENTS" MODIFY ("COMMENT_TEXT" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_COMMENTS" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
