REM INSERTING into INAP.UNITSHUB_ATP_GROUPS
SET DEFINE OFF;
Insert into INAP.UNITSHUB_ATP_GROUPS (PLAN_ID,GROUP_ID,GROUP_TITLE,SORT_ORDER,IMPLEMENT_ON,REFERENCE_PHRASE) values ('00001','00001','Reservation Fees',1,'1.1','Reservation for Unit [@Reference]');
