REM INSERTING into INAP.UNITSHUB_PERMISSIONS
SET DEFINE OFF;
Insert into INAP.UNITSHUB_PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,DESCRIPTION) values ('0001','VIEW',null);
Insert into INAP.UNITSHUB_PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,DESCRIPTION) values ('0002','INSERT',null);
Insert into INAP.UNITSHUB_PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,DESCRIPTION) values ('0003','EDIT',null);
Insert into INAP.UNITSHUB_PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,DESCRIPTION) values ('0004','DELETE',null);
Insert into INAP.UNITSHUB_PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,DESCRIPTION) values ('0005','PRINT',null);
Insert into INAP.UNITSHUB_PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,DESCRIPTION) values ('0006','EXPORT',null);
Insert into INAP.UNITSHUB_PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,DESCRIPTION) values ('0007','APPROVE',null);
Insert into INAP.UNITSHUB_PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,DESCRIPTION) values ('0008','MANAGE_SECURITY',null);
