REM INSERTING into INAP.UNITSHUB_UNITSSTATUS
SET DEFINE OFF;
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS,STATE_ID,SUBTITLE) values ('HANDED OVER','040',null);
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS,STATE_ID,SUBTITLE) values ('HELD','020',null);
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS,STATE_ID,SUBTITLE) values ('RESERVED','010',null);
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS,STATE_ID,SUBTITLE) values ('SOLD','030',null);
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS,STATE_ID,SUBTITLE) values ('VACANT','000','Ready To Reserve');
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS,STATE_ID,SUBTITLE) values ('MOCK-UP','100',null);
