REM INSERTING into INAP.UNITSHUB_DOC_CATEGORIES
SET DEFINE OFF;
Insert into INAP.UNITSHUB_DOC_CATEGORIES (CATEGORY_ID,PROJECT_ID,TITLE,SORT_ORDER,IS_ACTIVE) values ('0001','0017','Contracts',1,'Y');
Insert into INAP.UNITSHUB_DOC_CATEGORIES (CATEGORY_ID,PROJECT_ID,TITLE,SORT_ORDER,IS_ACTIVE) values ('0002','0017','Authentication Documents',2,'Y');
Insert into INAP.UNITSHUB_DOC_CATEGORIES (CATEGORY_ID,PROJECT_ID,TITLE,SORT_ORDER,IS_ACTIVE) values ('0003','0017','Unit Plans',3,'Y');
Insert into INAP.UNITSHUB_DOC_CATEGORIES (CATEGORY_ID,PROJECT_ID,TITLE,SORT_ORDER,IS_ACTIVE) values ('0004','0017','Receipts',4,'Y');
Insert into INAP.UNITSHUB_DOC_CATEGORIES (CATEGORY_ID,PROJECT_ID,TITLE,SORT_ORDER,IS_ACTIVE) values ('0005','0017','Other',9,'Y');
