REM INSERTING into INAP.UNITSHUB_NODE_TYPES
SET DEFINE OFF;
Insert into INAP.UNITSHUB_NODE_TYPES (NODE_TYPE_ID,TYPE_NAME,MUST_ATTRIBUTES) values ('001','BLOCK',null);
Insert into INAP.UNITSHUB_NODE_TYPES (NODE_TYPE_ID,TYPE_NAME,MUST_ATTRIBUTES) values ('002','BUILDING',null);
Insert into INAP.UNITSHUB_NODE_TYPES (NODE_TYPE_ID,TYPE_NAME,MUST_ATTRIBUTES) values ('003','FLOOR',null);
Insert into INAP.UNITSHUB_NODE_TYPES (NODE_TYPE_ID,TYPE_NAME,MUST_ATTRIBUTES) values ('004','APARTMENT','PAYMENTPLAN');
Insert into INAP.UNITSHUB_NODE_TYPES (NODE_TYPE_ID,TYPE_NAME,MUST_ATTRIBUTES) values ('000','PROJECT','#ACCOUNT');
Insert into INAP.UNITSHUB_NODE_TYPES (NODE_TYPE_ID,TYPE_NAME,MUST_ATTRIBUTES) values ('006','VILLA','PAYMENTPLAN');
