--------------------------------------------------------
--  Constraints for Table UNITSHUB_ATP_DETAILS
--------------------------------------------------------

  ALTER TABLE "INAP"."UNITSHUB_ATP_DETAILS" ADD PRIMARY KEY ("DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP"  ENABLE;
  ALTER TABLE "INAP"."UNITSHUB_ATP_DETAILS" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ATP_DETAILS" MODIFY ("ACCOUNT_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ATP_DETAILS" MODIFY ("GROUP_ID" NOT NULL ENABLE);
