--------------------------------------------------------
--  DDL for Table UNITSHUB_USERPERMISSIONS
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_USERPERMISSIONS" 
   (	"USER_ID" VARCHAR2(5 BYTE), 
	"RESOURCE_ID" VARCHAR2(5 BYTE), 
	"PERMISSION_ID" VARCHAR2(5 BYTE), 
	"ALLOW_DENY" CHAR(1 BYTE) DEFAULT 'A'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;
