REM INSERTING into INAP.UNITSHUB_ACCOUNTBRANCHPROJECTS
SET DEFINE OFF;
Insert into INAP.UNITSHUB_ACCOUNTBRANCHPROJECTS (ACCOUNTTYPE,BRANCH,PROJECTS) values ('593','100',null);
Insert into INAP.UNITSHUB_ACCOUNTBRANCHPROJECTS (ACCOUNTTYPE,BRANCH,PROJECTS) values ('606','850',null);
Insert into INAP.UNITSHUB_ACCOUNTBRANCHPROJECTS (ACCOUNTTYPE,BRANCH,PROJECTS) values ('594','100',null);
Insert into INAP.UNITSHUB_ACCOUNTBRANCHPROJECTS (ACCOUNTTYPE,BRANCH,PROJECTS) values ('594','200',null);
Insert into INAP.UNITSHUB_ACCOUNTBRANCHPROJECTS (ACCOUNTTYPE,BRANCH,PROJECTS) values ('609','100',null);
Insert into INAP.UNITSHUB_ACCOUNTBRANCHPROJECTS (ACCOUNTTYPE,BRANCH,PROJECTS) values ('606','100',null);
Insert into INAP.UNITSHUB_ACCOUNTBRANCHPROJECTS (ACCOUNTTYPE,BRANCH,PROJECTS) values ('606','160',null);
Insert into INAP.UNITSHUB_ACCOUNTBRANCHPROJECTS (ACCOUNTTYPE,BRANCH,PROJECTS) values ('607','160',null);
