--------------------------------------------------------
--  Constraints for Table UNITSHUB_ATP_GROUPS
--------------------------------------------------------

  ALTER TABLE "INAP"."UNITSHUB_ATP_GROUPS" ADD PRIMARY KEY ("GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP"  ENABLE;
  ALTER TABLE "INAP"."UNITSHUB_ATP_GROUPS" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ATP_GROUPS" MODIFY ("GROUP_TITLE" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ATP_GROUPS" MODIFY ("PLAN_ID" NOT NULL ENABLE);
