--------------------------------------------------------
--  DDL for Table UNITSHUB_USERS
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_USERS" 
   (	"USER_ID" VARCHAR2(5 BYTE), 
	"FULL_NAME" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"IS_ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"CREATED_ON" NUMBER, 
	"LAST_LOGIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;
