--------------------------------------------------------
--  DDL for Table UNITSHUB_COMMENTS
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_COMMENTS" 
   (	"COMMENT_ID" VARCHAR2(7 BYTE), 
	"PROJECT_ID" VARCHAR2(7 BYTE), 
	"NODE_ID" VARCHAR2(7 BYTE), 
	"CONTACT_ID" VARCHAR2(7 BYTE), 
	"DOCUMENT_ID" VARCHAR2(7 BYTE), 
	"COMMENT_TEXT" VARCHAR2(4000 BYTE), 
	"CREATED_BY" VARCHAR2(5 BYTE), 
	"CREATED_AT" NUMBER(12,0), 
	"IS_ACTIVE" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;

   COMMENT ON COLUMN "INAP"."UNITSHUB_COMMENTS"."DOCUMENT_ID" IS 'Optional link to a document the comment refers to (its own files are in UNITSHUB_ATTACHMENTS.COMMENT_ID)';
   COMMENT ON TABLE "INAP"."UNITSHUB_COMMENTS"  IS 'Free-text notes about a unit, a customer, or both';
