REM INSERTING into INAP.UNITSHUBX_PERMISSIONS
SET DEFINE OFF;
Insert into INAP.UNITSHUBX_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION) values ('0010','Details',null);
Insert into INAP.UNITSHUBX_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION) values ('0020','Show History',null);
Insert into INAP.UNITSHUBX_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION) values ('0030','Edit Info',null);
Insert into INAP.UNITSHUBX_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION) values ('0040','Keys',null);
Insert into INAP.UNITSHUBX_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION) values ('0050','Sell',null);
Insert into INAP.UNITSHUBX_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION) values ('0060','Vacant',null);
Insert into INAP.UNITSHUBX_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION) values ('0070','Reserve',null);
Insert into INAP.UNITSHUBX_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION) values ('0080','Hold',null);
Insert into INAP.UNITSHUBX_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION) values ('0090','Mock-Up',null);
Insert into INAP.UNITSHUBX_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION) values ('0100','Disable',null);
Insert into INAP.UNITSHUBX_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION) values ('0110','Implement Payment',null);
Insert into INAP.UNITSHUBX_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION) values ('0120','HandOver',null);
