REM INSERTING into INAP.UNITSHUB_PERMISSIONS
SET DEFINE OFF;
Insert into INAP.UNITSHUB_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION,ICON) values ('0010','Details','Open A Dialogue to show details','?');
Insert into INAP.UNITSHUB_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION,ICON) values ('0020','Show History',null,null);
Insert into INAP.UNITSHUB_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION,ICON) values ('0030','Edit Info',null,'?');
Insert into INAP.UNITSHUB_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION,ICON) values ('0040','Keys',null,null);
Insert into INAP.UNITSHUB_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION,ICON) values ('0050','Sell',null,null);
Insert into INAP.UNITSHUB_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION,ICON) values ('0060','Vacant',null,null);
Insert into INAP.UNITSHUB_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION,ICON) values ('0070','Reserve',null,null);
Insert into INAP.UNITSHUB_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION,ICON) values ('0080','Hold',null,null);
Insert into INAP.UNITSHUB_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION,ICON) values ('0090','Mock-Up',null,null);
Insert into INAP.UNITSHUB_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION,ICON) values ('0100','Disable',null,null);
Insert into INAP.UNITSHUB_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION,ICON) values ('0110','Implement Payment',null,null);
Insert into INAP.UNITSHUB_PERMISSIONS (ACTION_ID,PERMISSION_NAME,DESCRIPTION,ICON) values ('0120','HandOver',null,null);
