REM INSERTING into INAP.UNITSHUB_ENTITIES
SET DEFINE OFF;
Insert into INAP.UNITSHUB_ENTITIES (ENTITY_ID,ENTITY_NAME) values ('0001','Unit');
Insert into INAP.UNITSHUB_ENTITIES (ENTITY_ID,ENTITY_NAME) values ('0002','Customer');
