REM INSERTING into INAP.UNITSHUB_NODE_TYPES
SET DEFINE OFF;
Insert into INAP.UNITSHUB_NODE_TYPES (NODE_TYPE_ID,TYPE_NAME) values ('001','BLOCK');
Insert into INAP.UNITSHUB_NODE_TYPES (NODE_TYPE_ID,TYPE_NAME) values ('002','BUILDING');
Insert into INAP.UNITSHUB_NODE_TYPES (NODE_TYPE_ID,TYPE_NAME) values ('003','FLOOR');
Insert into INAP.UNITSHUB_NODE_TYPES (NODE_TYPE_ID,TYPE_NAME) values ('004','APARTMENT');
Insert into INAP.UNITSHUB_NODE_TYPES (NODE_TYPE_ID,TYPE_NAME) values ('000','PROJECT');
Insert into INAP.UNITSHUB_NODE_TYPES (NODE_TYPE_ID,TYPE_NAME) values ('006','VILLA');
