--------------------------------------------------------
--  DDL for Table UNITSHUB_AUTOTRANSFER_DONE_D
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_AUTOTRANSFER_DONE_D" 
   (	"UNITPAYMENT_ID" VARCHAR2(7 BYTE), 
	"ENTRY" NUMBER(5,0), 
	"ACCOUNT" VARCHAR2(30 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"TRANSACTION" CHAR(1 BYTE), 
	"AMOUNT" NUMBER(18,3), 
	"REFERENCE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"DATENTIME" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;
