--------------------------------------------------------
--  Constraints for Table UNITSHUB_PRJ_STS_ACTN_USRS
--------------------------------------------------------

  ALTER TABLE "INAP"."UNITSHUB_PRJ_STS_ACTN_USRS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_PRJ_STS_ACTN_USRS" MODIFY ("ACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_PRJ_STS_ACTN_USRS" MODIFY ("STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_PRJ_STS_ACTN_USRS" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
