REM INSERTING into INAP.UNITSHUB_GROUPROLES
SET DEFINE OFF;
Insert into INAP.UNITSHUB_GROUPROLES (GROUP_ID,ROLE_ID) values ('0001','0001');
Insert into INAP.UNITSHUB_GROUPROLES (GROUP_ID,ROLE_ID) values ('0002','0002');
Insert into INAP.UNITSHUB_GROUPROLES (GROUP_ID,ROLE_ID) values ('0003','0003');
