REM INSERTING into INAP.UNITSHUB_PAYMENTPLANDETAILS
SET DEFINE OFF;
Insert into INAP.UNITSHUB_PAYMENTPLANDETAILS (DETAIL_ID,PLAN_ID,DESCRIPTION,PERCENT,AMOUNT,FORMULA) values ('1','1','Reservation','5%',null,'200');
Insert into INAP.UNITSHUB_PAYMENTPLANDETAILS (DETAIL_ID,PLAN_ID,DESCRIPTION,PERCENT,AMOUNT,FORMULA) values ('2','1','2nd Installment','90%',null,'30%*[UnitPrice]-200');
Insert into INAP.UNITSHUB_PAYMENTPLANDETAILS (DETAIL_ID,PLAN_ID,DESCRIPTION,PERCENT,AMOUNT,FORMULA) values ('3','1','Final Installment','5%',null,'[70%]*[UnitPrice]');
