REM INSERTING into INAP.UNITSHUB_UNITSSTATUS
SET DEFINE OFF;
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR) values ('HANDED OVER','040',null,null,null,null,null);
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR) values ('HELD','020',null,'bcb100',null,null,null);
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR) values ('RESERVED','010',null,'6dbfff','000000',null,null);
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR) values ('SOLD','030',null,'357d00','FFFFFF',null,null);
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR) values ('VACANT','000','Ready To Reserve','f7e494','000000','FFFFFF','000000');
Insert into INAP.UNITSHUB_UNITSSTATUS (STATUS,STATE_ID,SUBTITLE,STATUS_BG_COLOR,STATUS_FG_COLOR,SUBTITLE_BG_COLOR,SUBTITLE_FG_COLOR) values ('MOCK-UP','100',null,'aeaeae','000000',null,null);
