--------------------------------------------------------
--  DDL for Table UNITSHUB_ACT_PAY_PLN_DETAILS
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_ACT_PAY_PLN_DETAILS" 
   (	"PROJECT_ID" VARCHAR2(5 BYTE), 
	"STATUS_ID" VARCHAR2(5 BYTE), 
	"ACTION_ID" VARCHAR2(5 BYTE), 
	"PLAN_ID" VARCHAR2(50 BYTE), 
	"DETAIL_ID" VARCHAR2(50 BYTE), 
	"ID" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;
