--------------------------------------------------------
--  Constraints for Table UNITSHUB_ATTACHMENTS
--------------------------------------------------------

  ALTER TABLE "INAP"."UNITSHUB_ATTACHMENTS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ATTACHMENTS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ATTACHMENTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ATTACHMENTS" MODIFY ("STORED_PATH" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ATTACHMENTS" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "INAP"."UNITSHUB_ATTACHMENTS" MODIFY ("ATTACHMENT_ID" NOT NULL ENABLE);
