--------------------------------------------------------
--  DDL for Table UNITSHUB_DOCUMENTS
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_DOCUMENTS" 
   (	"DOCUMENT_ID" VARCHAR2(7 BYTE), 
	"CATEGORY_ID" VARCHAR2(4 BYTE), 
	"PROJECT_ID" VARCHAR2(7 BYTE), 
	"NODE_ID" VARCHAR2(7 BYTE), 
	"CONTACT_ID" VARCHAR2(7 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"DOC_DATE" DATE, 
	"EXPIRY_DATE" DATE, 
	"NOTES" VARCHAR2(1000 BYTE), 
	"CREATED_BY" VARCHAR2(5 BYTE), 
	"CREATED_AT" NUMBER(12,0), 
	"IS_ACTIVE" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;

   COMMENT ON COLUMN "INAP"."UNITSHUB_DOCUMENTS"."NODE_ID" IS 'Unit the document is about (NULL = customer-only document)';
   COMMENT ON COLUMN "INAP"."UNITSHUB_DOCUMENTS"."CONTACT_ID" IS 'Customer the document is about (NULL = unit-only document)';
   COMMENT ON TABLE "INAP"."UNITSHUB_DOCUMENTS"  IS 'A titled document in a category, about a unit, a customer, or both';
