--------------------------------------------------------
--  DDL for Table UNITSHUB_UNITSHISTORY
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_UNITSHISTORY" 
   (	"PROJECT_ID" VARCHAR2(7 BYTE), 
	"NODE_ID" VARCHAR2(7 BYTE), 
	"FROM_STATUS" VARCHAR2(5 BYTE), 
	"TO_STATUS" VARCHAR2(5 BYTE), 
	"PAYMENT_PLAN" VARCHAR2(7 BYTE), 
	"ACTION_ID" VARCHAR2(7 BYTE), 
	"PAYMENTS" VARCHAR2(150 BYTE), 
	"PAYMENTSROWS" VARCHAR2(150 BYTE), 
	"AUTOTRANSFER" VARCHAR2(150 BYTE), 
	"AUTOTRANSFERROWS" VARCHAR2(150 BYTE), 
	"IMPLEMENTEDBY" VARCHAR2(5 BYTE), 
	"WORKSTATION" VARCHAR2(5 BYTE), 
	"CONTACT_ID" VARCHAR2(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;

   COMMENT ON COLUMN "INAP"."UNITSHUB_UNITSHISTORY"."PAYMENTS" IS 'Transaction numbers as they are in ICBS';
   COMMENT ON COLUMN "INAP"."UNITSHUB_UNITSHISTORY"."PAYMENTSROWS" IS 'Rows IDs in UNITSHUB_PAYMENTS';
   COMMENT ON COLUMN "INAP"."UNITSHUB_UNITSHISTORY"."AUTOTRANSFER" IS 'Transaction numbers as they are in ICBS';
   COMMENT ON COLUMN "INAP"."UNITSHUB_UNITSHISTORY"."AUTOTRANSFERROWS" IS 'Rows IDs in UNITSHUB_PAYMENTS';
