REM INSERTING into INAP.UNITSHUB_VIEWS
SET DEFINE OFF;
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('001','PROJECT',1,'UNITSHUB_PRJ001_PROJECTS',null);
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('001','BLOCK',2,'UNITSHUB_PRJ001_BLOCKS',null);
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('001','BUILDING',3,'UNITSHUB_PRJ001_BUILDINGS',null);
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('001','APARTMENT',4,'UNITSHUB_PRJ001_APARTMMENTS',null);
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('002','PROJECT',1,'UNITSHUB_PRJ002_PROJECTS',null);
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('002','BLOCK',2,'UNITSHUB_PRJ002_BLOCKS',null);
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('002','BUILDING',3,'UNITSHUB_PRJ002_BUILDINGS',null);
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('002','APARTMENT',4,'UNITSHUB_PRJ002_APARTMENTS',null);
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('003','PROJECT',1,'UNITSHUB_PRJ003_PROJECT',null);
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('003','BUILDING',2,'UNITSHUB_PRJ003_BUILDINGS',null);
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('003','APARTMENT',3,'UNITSHUB_PRJ003_APARTMENT',null);
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('004','PROJECT',1,'UNITSHUB_PRJ004_PROJECT',null);
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('004','VILLA',2,'UNITSHUB_PRJ004_VILLAS',null);
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('005','PROJECT',1,'UNITSHUB_PRJ005_PROJECT',null);
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('005','VILLA',2,'UNTISHUB_PRJ005_VILLAS',null);
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('006','PROJECT',1,'UNITSHUB_PRJ006_PROJECT',null);
Insert into INAP.UNITSHUB_VIEWS (PROJECT_ID,TYPE_NAME,TREELEVEL,VIEWNAME,COMMENTS) values ('006','VILLA',2,'UNITSHUB_PRJ006_VILLAS',null);
