--------------------------------------------------------
--  DDL for Table UNITSHUB_AUTOTRANSFER_DONE
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_AUTOTRANSFER_DONE" 
   (	"NODEID" VARCHAR2(10 BYTE), 
	"CONTACT_ID" VARCHAR2(10 BYTE), 
	"PLAN_ID" VARCHAR2(3 BYTE), 
	"SEQ" VARCHAR2(3 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"AMOUNT" VARCHAR2(15 BYTE), 
	"DATEPAID" VARCHAR2(20 BYTE), 
	"TIMEPAID" VARCHAR2(8 BYTE), 
	"NARRATIVE" VARCHAR2(500 BYTE), 
	"TRANSACTIONID" VARCHAR2(20 BYTE), 
	"PERCENT" VARCHAR2(10 BYTE), 
	"ACTIVE" VARCHAR2(2 BYTE), 
	"DATECREATED" VARCHAR2(20 BYTE), 
	"PDF" VARCHAR2(20 BYTE), 
	"PAYMENT_ID" VARCHAR2(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;
