--------------------------------------------------------
--  DDL for Table UNITSHUB_ACTION_PLACEMENTS
--------------------------------------------------------

  CREATE TABLE "INAP"."UNITSHUB_ACTION_PLACEMENTS" 
   (	"PROJECT_ID" VARCHAR2(5 BYTE), 
	"ACTION_ID" VARCHAR2(5 BYTE), 
	"STATUS_ID" VARCHAR2(5 BYTE), 
	"SUBSTATE_ID" VARCHAR2(5 BYTE) DEFAULT '*', 
	"TO_STATUS_ID" VARCHAR2(5 BYTE), 
	"TO_SUBSTATE_ID" VARCHAR2(5 BYTE), 
	"SORT_ORDER" NUMBER(4,0), 
	"IS_ACTIVE" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INAP" ;
